### ISSUE TITLE
pipeline _readqc report failure

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#203]
using build_report fails to build the report or even create the report directory for the readqc pipeline and I can't track down the error. This happens in several different projects I've tried it in and in projects where it worked fine 10 days ago. 

The pipeline.log output is:
## 2016-04-28 14:08:30,962 INFO Tasks which will be run:
#2016-04-28 14:08:30,962 INFO
#2016-04-28 14:08:30,963 INFO
## 2016-04-28 14:08:33,231 DEBUG running statement:
# rm -rf report _cache _static;     (export SPHINX_DOCSDIR=/ifs/devel/charlotteg/CGATPipelines/CGATPipelines/pipeline_docs/pipeline_readqc;     export SPHINX_THEMEDIR=/ifs/devel/charlotteg/CGATPipelines/CGATPipelines/pipeline_docs/themes;     export PYTHONPATH=/ifs/devel/charlotteg/CGATPipelines/CGATPipelines:/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages:/ifs/apps/bio/sicer-1.1/lib:/ifs/apps/bio/alignlib/lib/python2.7/site-packages:/ifs/devel/charlotteg/CGATPipelines:/ifs/devel/charlotteg/cgat:/ifs/devel/charlotteg/python/lib/python27.zip:/ifs/devel/charlotteg/python/lib/python2.7:/ifs/devel/charlotteg/python/lib/python2.7/plat-linux2:/ifs/devel/charlotteg/python/lib/python2.7/lib-tk:/ifs/devel/charlotteg/python/lib/python2.7/lib-old:/ifs/devel/charlotteg/python/lib/python2.7/lib-dynload:/ifs/apps/apps/python-2.7.11/lib/python2.7:/ifs/apps/apps/python-2.7.11/lib/python2.7/plat-linux2:/ifs/apps/apps/python-2.7.11/lib/python2.7/lib-tk:/ifs/devel/charlotteg/python/lib/python2.7/site-packages:/ifs/devel/charlotteg/python/lib/python2.7/site-packages:/ifs/apps/src/Python-2.7.11/nbconvert:/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport-0.3.7-py2.7.egg;     /usr/bin/xvfb-run -a      cgatreport-build     --num-jobs=10     sphinx-build     -b html     -d report/doctrees     -c .     -j 10     /ifs/devel/charlotteg/CGATPipelines/CGATPipelines/pipeline_docs/pipeline_readqc report/html     >& report.log || true )
## 2016-04-28 14:09:05,721 INFO # job finished in 35 seconds at Thu Apr 28 14:09:05 2016 --  1.48  0.49  0.14  0.11 -- 528e41c2-f4ba-462d-ae33-29578142dfe7

The report location does not exist. 

Here is the report.log output 
Traceback (most recent call last):
  File "/ifs/home/charlotteg/python/bin/cgatreport-build", line 9, in <module>
    load_entry_point('CGATReport', 'console_scripts', 'cgatreport-build')()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/build.py", line 40, in <module>
    from CGATReport import report_directive, clean, Utils
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/report_directive.py", line 474, in <module>
    class report_directive(Directive):
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/report_directive.py", line 481, in report_directive
    option_spec = Component.getOptionSpec()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/Component.py", line 150, in getOptionSpec
    o = getOptionMap()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/Component.py", line 103, in getOptionMap
    for section, plugins in getPlugins().items():
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/Component.py", line 86, in getPlugins
    plugins = init_plugins()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/CGATReport/Component.py", line 59, in init_plugins
    pkg_env = pkg_resources.Environment()
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1020, in **init**
    self.scan(search_path)
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1049, in scan
    for dist in find_distributions(item):
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1996, in find_on_path
    for item in dists:
..........
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1982, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2370, in from_location
    py_version=py_version, platform=platform, **kw
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2349, in **init**
    self._version = safe_version(version)
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1387, in safe_version
    return str(packaging.version.Version(version))
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 230, in __init__
    self._version.local,
  File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 353, in _cmpkey
    reversed(release),
RuntimeError: maximum recursion depth exceeded

**Comment by MikeDMorgan** [comment]
I've noticed the same this with pipeline_readqc.py, and it also applies to pipeline_mapping.  The CGATreport.log only contains a single line:
`2016-04-28 14:46:18,758 INFO initialising plugins`

@AndreasHeger is this CGATReport or SphinxReport?

**Comment by jscaber** [comment]
I agree, it applies to all pipeline reports.
My guess is it's got to do with our local python installation:
There is an infinite loop and hence the `RuntimeError: maximum recursion depth exceeded`
It hangs here:

```
 File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1049, in scan
    for dist in find_distributions(item):
File "/ifs/apps/apps/python-2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1996, in find_on_path
    for item in dists:
```

The last line is run >1000 times in my report.log

**Comment by AndreasHeger** [comment]
Hi,

probably something I messed up. Will take a look tonight and fix
the install.

Best,
Andreas

**Comment by logust79** [comment]
I think it was me. Sebastian had similar issue after finding out that somehow I messed up the central python copy. Although I already forgot what I did!

Sorry
Jing

**Comment by AndreasHeger** [comment]
Did you type python setup.py develop or install outside your virtual
environment?

Best wishes,
Andreas

**Comment by logust79** [comment]
It turns out that I never used my virtual environment due to a missing line in my bashrc, and I never realised this until now.

Jing

**Comment by sebastian-luna-valero** [comment]
Thanks @AndreasHeger  for the fix!
