### ISSUE TITLE
pipeline_peakcalling - runSPP.py does not function

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#31]
runSPP.py does fails with error

Traceback (most recent call last):
  File "/ifs/devel/charlotteg/cgat/scripts/runSPP.py", line 300, in <module>
    sys.exit(main(sys.argv))
  File "/ifs/devel/charlotteg/cgat/scripts/runSPP.py", line 235, in main
    cluster=cluster);''' % locals())
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/rpy2/robjects/**init**.py", line 246, in **call**
    res = self.eval(p)
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in **call**
    return super(SignatureTranslatedFunction, self).**call**(_args, *_kwargs)
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in **call**
    res = super(Function, self).**call**(_new_args, *_new_kwargs)
rpy2.rinterface.RRuntimeError: Error in names(cc) <- names(otl) : attempt to set an attribute on NULL

This causes  loadSPP to evaluate to None - peak calling with SPP does not currently function in this pipeline.

**Comment by AndreasHeger** [comment]
Hi @Charlie-George , is still an issue? It seems to work for me.
Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closed for now
