### ISSUE TITLE
pipeline_rnaseqqc.py: AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'replace'

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#334]
Hi,

When running `pipeline_testing.py` with the latest pandas version `0.20.1`, I get the error below in `pipeline_rnaseqqc`.

```

                                                      'exceptions.AttributeError('pandas._libs.interval.Interval' object has no attribute 'replace')' raised in ...
                                                       Task = def summariseBias(...):
                                                       Job  = [[geneset.dir/transcripts_attributes.tsv.gz, sailfish.dir/sailfish_genes.tsv.gz, sailfish.dir/sailfish_transcripts.tsv.gz] -> geneset.dir/bias_binned_means.tsv]
                                                    
                                                    Traceback (most recent call last):
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
                                                        register_cleanup, touch_files_only)
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
                                                        ret_val = user_defined_work_func(*params)
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/CGATPipelines/CGATPipelines/pipeline_rnaseqqc.py", line 1518, in summariseBias
                                                        merged, factor, samples, PARAMS["bias_bin"], np.mean)
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/CGATPipelines/CGATPipelines/pipeline_rnaseqqc.py", line 1504, in aggregate_by_factor
                                                        means_df[attribute] = [np.mean(bin2floats(x)) for x in atr_values]
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/CGATPipelines/CGATPipelines/pipeline_rnaseqqc.py", line 1479, in bin2floats
                                                        qcut_bin2 = qcut_bin.replace("(", "[").replace(")", "]")
                                                    AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'replace'

```

@TomSmithCGAT could you please have a [look](https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_rnaseqqc.py#L1479) when you have a spare time? or should we stick to the previous pandas version as the new one break things?

Best regards,
Sebastian

**Comment by TomSmithCGAT** [comment]
I'll have a look soon. I think we should support the latest pandas.

**Comment by sebastian-luna-valero** [comment]
Thanks!

**Comment by sebastian-luna-valero** [comment]
When running the `test_import` script for pipelines, I have just seen this:
```
/ifs/devel/sebastian/code-py3-2017-05-02/CGATPipelines/CGATPipelines/PipelineRnaseq.py ... /ifs/devel/sebastian/py3-2017-05-02/lib/python3.5/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
  from pandas.lib import Timestamp
/ifs/devel/sebastian/py3-2017-05-02/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
```
I thought it could be relevant to this issue.

**Comment by sebastian-luna-valero** [comment]
This issue doesn't happen with the Python 3 environment, so closing.
