### ISSUE TITLE
trim_galore in readqc

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/CGATPipelines#387]
When using `trim_galore` in `pipeline_readqc.py`, the following exception occurs:
```

    Exception #4
      'builtins.OSError(---------------------------------------
    Child was terminated by signal 1:
    The stderr was:
    mv: cannot stat `processed.dir/trimmed-Brain-F2-R2-trimgalore_trimmed.fq.gz': No such file or directory
   
    mkdir -p /ifs/scratch/ctmpt8mm339v; checkpoint; trim_galore -q 20 --length 40 --rrbs -a AGATCGGAAGAGC             --phred33             --output_dir processed.dir             Brain-F2-R2.fastq.gz             2>>processed.dir/trimmed-Brain-F2-R2-trimgalore.log;             mv processed.dir/trimmed-Brain-F2-R2-trimgalore_trimmed.fq.gz processed.dir/trimmed-Brain-F2-R2.fastq.gz;              checkpoint; rm -rf /ifs/scratch/ctmpwlrlxvp2;rm -rf /ifs/scratch/ctmpt8mm339v
    -----------------------------------------)' raised in ...
       Task = def pipeline_readqc.processReads(...):
       Job  = [Brain-F2-R2.fastq.gz -> processed.dir/trimmed-Brain-F2-R2.fastq*.gz]
   
    Traceback (most recent call last):
      File "/ifs/devel/hashem/cgat-code/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/ifs/devel/hashem/cgat-code/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/ifs/devel/hashem/cgat-code/cgat-pipelines/CGATPipelines/pipeline_readqc.py", line 311, in processReads
        P.run()
      File "/ifs/devel/hashem/cgat-code/cgat-pipelines/CGATPipelines/Pipeline/Execution.py", line 550, in run
        ignore_errors=ignore_errors)
      File "/ifs/devel/hashem/cgat-code/cgat-pipelines/CGATPipelines/Pipeline/Cluster.py", line 329, in collectSingleJobFromCluster
        "".join(stderr), statement))
```

The pipeline task `processReads` is expecting:
* `processed.dir/trimmed-Brain-F2-R2-trimgalore_trimmed.fq.gz`

in this step:
* ` mv processed.dir/trimmed-Brain-F2-R2-trimgalore_trimmed.fq.gz processed.dir/trimmed-Brain-F2-R2.fastq.gz`

and the following file is being generated instead:
* `processed.dir/Brain-F2-R2_trimmed.fq.gz`

**Comment by AndreasHeger** [comment]
My guess that trimgalore is a new version?

**Comment by sebastian-luna-valero** [comment]
Thanks @AndreasHeger 

I rerun the pipeline with older versions of `trim_galore` available as module files. Version 0.3.3 did not work since it requires Python 2.7. Version 0.4.4 generated the same problem.

The issue seems to  be fixed with the change in https://github.com/CGATOxford/CGATPipelines/pull/391
